version: '3'

services:
  imposto_renda:
    container_name: unisoma_teste_imposto_renda
    build:
      context: .
      dockerfile: exercio2\Dockerfile
    depends_on:
      - api
    ports:
    - 8082:8080
  api:
    container_name: unisoma_teste_api_geral
    build: 
      context: .
      dockerfile: exercios1\Dockerfile
    depends_on:
      - database
    ports:
    - 8081:8080
  database:
    container_name: unisoma_teste_database
    image: postgres
    environment:
      POSTGRES_DB: unisoma_teste
      POSTGRES_USER: unisoma
      POSTGRES_PASSWORD: teste
    ports:
    - 5433:5432